version: '3.9'

services:
  app:
    image: balbatross/sapro-bio-plant:main
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - /home/ubuntu/pg:/var/lib/postgresql/data
    environment:
      - POSTGRESS_PASSWORD=test